### ISSUE TITLE
Is Scala 3 supported?

### ISSUE THREAD

**Issue by ice-bergg** [onsqcorp/scala-android-plugin#1]
Hey, as in the title - does the plugin support glorious Scala 3?

**Comment by onsquareDev** [comment]
No, Android Build Tool is not compatible with Scala 3.

**Comment by ice-bergg** [comment]
Thanks!

**Comment by mcallisto** [comment]
@onsquareDev @ice-bergg it seems to me that it can support Scala 3, see my fork of the demo app https://github.com/mcallisto/hello-scala-android with

* Scala 3.7.0-RC1
* AGP 8.9.1
* SDK 35
* JDK 17

**Comment by mcallisto** [comment]
>     * Scala 3.7.0-RC1

By the way, it is working with Scala 3.6.4 as well.
3.7.0-RC1 is interesting for Android because is the first Scala version shipping https://github.com/scala/scala3/pull/22632.

**Comment by pocorall** [comment]
Oh it really works! Thank you for the good news.

And I also would like to merge your changes to the hello-scala-android project, if you'd like.

**Comment by onsquareDev** [comment]
Oh it really works! Thank you for the good news.

And I also would like to merge your changes to the hello-scala-android project, if you'd like.

**Comment by mcallisto** [comment]
> And I also would like to merge your changes to the hello-scala-android project, if you'd like.

Sure, I have submitted this https://github.com/onsqcorp/hello-scala-android/pull/1 PR.

Thank you @onsquareDev  for the good work on the plugin.
You may be interested to know that:
-  I started using it in this  https://github.com/mcallisto/Scala-3-Android-Studio-Java-template
-  there is an ongoing effort in the Scala community to facilitate the usage of Scala 3 in Android
-  there is a Discord > Scala > scala-android channel to share experiences and ideas https://discord.gg/aQCZ7QmP
