### ISSUE TITLE
Android Studio support

### ISSUE THREAD

**Issue by akumaigorodski** [onsqcorp/scala-android-plugin#2]
I've tried to apply this plugin to my app here: https://github.com/akumaigorodski/wallet/commit/a8f43f8b2a6ffa78a61e7a23cbe11711231705df.

The good news is that overall everything compiles and works, however I prefer to develop this app in `Android Studio Koala | 2024.1.1 Patch 1` (AS) and it behaves weirdly, so I'd like to ask if listed issues are somehow related to plugin and whether AS support is in scope of this project.

I've noticed two major issues so far:

- `R._` is not visible by AS and it highlights related imports as non-existent namespaces, so it's hard to work with all kinds of resources since AS thinks they are syntax errors.
- There seem to be no proper Scala syntax support, for example added Scala code in app example is syntax error according to AS:

```scala
override def onCreate(savedInstanceState: Bundle): Unit = {
    super.onCreate(savedInstanceState)
    val view = new TextView(this)
    val list = List(1,2,3).map(_ * 2) // syntax error
    view.setText(s"Hello Scala Android, $list") // syntax error
    setContentView(view)
  }
```

Although app still compiles and correctly shows an interpolated string.

**Comment by onsquareDev** [comment]
That is the problem of several versions of Android Studio. Use Android Studio Koala Feature Drop or later. [Here is a related issue report](https://youtrack.jetbrains.com/issue/SCL-22699/Incorrect-error-highlight-on-Android-Studio-Jellyfish) in Jetbrains issue tracker.

**Comment by akumaigorodski** [comment]
Thanks, I've installed `Android Studio Ladybug | 2024.2.1` and it did fix Scala syntax issue, but `R._` still remains even with locally compiled latest plugin version, here's an update code example:  

```scala
override def onCreate(savedInstanceState: Bundle): Unit = {
    super.onCreate(savedInstanceState)
    val view = new TextView(this)
    // R is red, namespace does not exist, 
    // however app compiles fine and "HelloScala" is found
    val appName = getString(com.soundcorset.helloscala.R.string.app_name)
    view.setText(s"Hello Scala Android $appName")
    setContentView(view)
  }
```

 I wonder if you experience anything similar or it's just specifics of my setup?
 
 UPD:

Did some quick look at scalroid source code and it seems to be doing some `R.jar` inclusion stuff here: https://github.com/chenakam/scalroid/blob/main/src/main/groovy/cash/bdo/ScalaAndroidCompatPlugin.groovy#L764-L781

I don't quite understand what is it exactly that it does but in my case `$ java -jar '/home/anton/Downloads/cfr-0.152.jar' '/home/anton/Desktop/hello-scala-android/app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debug/processDebugResources/R.jar'` does reveal app-related resources, maybe this info could be of help.

**Comment by onsquareDev** [comment]
Previously Android Build Tools generated `R.java` source code, and it was correctly recognized in the IntelliJ Scala IDE plugin. Somewhere around the year of 2020, Android Build Tools was changed to directly generate `R.class`, and in my theory (not 100% sure though), they forgot to correctly set up dependency for the newly generated `R.class`, so IntelliJ Scala IDE plugin failed to resolve it. In `build.gradle.kts` of your project, adding the code below solves the situation:

```
dependencies {
    compileOnly(fileTree(layout.buildDirectory) { include("**/R.jar") })
}
```

This is less precise than the @chenakam’s solution you referenced. But it is simpler, and it just works.

**Comment by akumaigorodski** [comment]
Indeed this does fix an `R` issue, thanks again.
